#ifndef MOVIE_H
#define MOVIE_H

#include <string>
#include <cstdint>

using namespace std;

struct Movie {
	int32_t movieID = 0;           // Unique identifier for the movie
	string title = "";             // Title of the movie
	string genre = "";             // Genre of the movie
	string originalLanguage = "";  // Original language of the movie
	string overview = "";          // Overview or summary of the movie
	double popularity = 0.0;        // Popularity score of the movie
	string productionCompanies = ""; // Production companies involved in the movie
	string releaseDate = "";       // Release date of the movie
	int32_t budget = 0;             // Budget of the movie
	int32_t revenue = 0;            // Revenue generated by the movie
	int runtime = 0;             // Runtime of the movie in minutes
	string status = "";           // Status of the movie (e.g., "Released", "In Production")
	string tagline = "";          // Tagline of the movie
	double voterAverage = 0.0;     // Average rating from voters
	int voterCount = 0;          // Number of voters who rated the movie
	string credits = "";          // Credits associated with the movie (e.g., cast and crew)
	string keywords = "";         // Keywords related to the movie
	string posterPath = "";       // Path to the poster image of the movie
	string backdropPath = "";     // Path to the backdrop image of the movie
	string recommendations = "";  // Recommendations based on this movie
    int32_t popularityRank = 0;

    Movie() {
    }

    Movie(int movieId, const string& movieTitle, const string& movieGenres,
          const string& language, const string& movieOverview,
          double moviePopularity, int rank, const string& date,
          int32_t movieBudget, int32_t movieRevenue,
          const string& companies) {
        movieID = movieId;
        title = movieTitle;
        genre = movieGenres;
        originalLanguage = language;
        overview = movieOverview;
        popularity = moviePopularity;
        popularityRank = rank;
        releaseDate = date;
        budget = movieBudget;
        revenue = movieRevenue;
        productionCompanies = companies;
    }
};

enum SortType { BY_MOVIEID, BY_RANK };

#endif