// Class definition for TreeNode, which represents a node in a Red Black tree used to store movie data.

#pragma once
#include <string>
#include <vector>
using namespace std;

// TreeNode class definition
struct TreeNode {
	long movieID;           // Unique identifier for the movie
	string title;             // Title of the movie
	string genre;             // Genre of the movie
	string originalLanguage;  // Original language of the movie
	string overview;          // Overview or summary of the movie
	double popularity;        // Popularity score of the movie
	int popularityRank;       // Popularity by rank (top 1, 2, etc...)
	string productionCompanies; // Production companies involved in the movie
	string releaseDate;       // Release date of the movie
	long budget;             // Budget of the movie
	long revenue;            // Revenue generated by the movie
	int runtime;             // Runtime of the movie in minutes
	string status;           // Status of the movie (e.g., "Released", "In Production")
	string tagline;          // Tagline of the movie
	double voterAverage;     // Average rating from voters
	int voterCount;          // Number of voters who rated the movie
	string credits;          // Credits associated with the movie (e.g., cast and crew)
	string keywords;         // Keywords related to the movie
	string posterPath;       // Path to the poster image of the movie
	string backdropPath;     // Path to the backdrop image of the movie
	string recommendations;  // Recommendations based on this movie
	bool isRed;             // Color of the node (true for red, false for black)
	TreeNode* left;         // Pointer to the left child node
	TreeNode* right;        // Pointer to the right child node
	TreeNode* parent;       // Pointer to the parent node
	// Constructor to initialize a TreeNode with default values
	TreeNode() : popularityRank(0), isRed(true), left(nullptr), right(nullptr), parent(nullptr) {}
};


class redBlackTree {
public:
	enum SortType { BY_MOVIEID, BY_POPULARITY, BY_REVENUE };
	redBlackTree(SortType sortType = BY_MOVIEID);


	// Public member functions for the red-black tree creation and manipulation
	void insert(TreeNode* node);
	void rotateLeft(TreeNode* node);
	void rotateRight(TreeNode* node);
	void balanceInsert(TreeNode* node);
	double getMostPopularMovie();
	long getHighestRevenueMovie();
	void searchByMovieID(long movieID);
	TreeNode* searchByRank(int rank);
	vector <TreeNode*> levelOrderTraversal();
private:
	TreeNode* root;
	SortType sortBy;
	TreeNode* searchRankHelper(TreeNode* node, int rank);
};

class SplayTree {
public:
	enum SortType { BY_RANK, BY_MOVIEID };

private:
	struct SplayNode {
		TreeNode data;
		SplayNode* left;
		SplayNode* right;

		SplayNode(const TreeNode& movie);
	};

	SplayNode* root;
	SortType sortBy;

	SplayNode* rightRotate(SplayNode* x);
	SplayNode* leftRotate(SplayNode* x);
	SplayNode* splay(SplayNode* currentRoot, long key);
	SplayNode* insert(SplayNode* currentRoot, const TreeNode& movie);
	SplayNode* searchMovieIDHelper(SplayNode* node, long movieID);

	void destroyTree(SplayNode* node);
	SplayNode* searchRankHelper(SplayNode* node, int rank);
	long getKey(const TreeNode& movie);

public:
	SplayTree(SortType sortType = BY_RANK);
	~SplayTree();

	void insert(TreeNode* node);

	TreeNode* searchByRank(int rank);
	vector<TreeNode*> levelOrderTraversal();
	double getMostPopularMovie();
	long getHighestRevenueMovie();
	void searchByMovieID(long movieID);
};